FROM python:3.13

# Add tini
RUN apt-get update && apt-get install -y tini

# upgrade pip
RUN pip install --upgrade pip

# install requirements
COPY requirements-backend.txt requirements.txt
RUN pip3 install -r requirements.txt --no-cache-dir

# playwright sucks and needs to be installed again???
RUN ["playwright", "install", "--with-deps", "chromium"]

# copy all files 
COPY /sdk /sdk
COPY Controller.py Controller.py
COPY main.py main.py
COPY api.py api.py

# Use tini as entrypoint
ENTRYPOINT ["/usr/bin/tini", "--"]

# Use shell form to properly handle signals
CMD python3 -u main.py