FROM python:3.9-alpine

# RUN apt-get update && apt-get install wget gcc -y

# install requirements
COPY requirements-api.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt


# copy all files
COPY /sdk /sdk
COPY Controller.py Controller.py
COPY main.py main.py
COPY api.py api.py


CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]