FROM python:3.9

# RUN apt-get update && apt-get install wget gcc -y

# install requirements
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt --no-cache-dir option 


# copy all files
COPY /sdk /sdk
COPY Controller.py Controller.py
COPY main.py main.py
COPY api.py api.py


CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]