FROM mcr.microsoft.com/playwright/python as build

# Add tini
RUN apt-get update && apt-get install -y tini

# install requirements
COPY requirements-backend.txt requirements.txt
RUN pip3 install -r requirements.txt --no-cache-dir

# copy all files 
COPY /sdk /sdk
COPY Controller.py Controller.py
COPY main.py main.py
COPY api.py api.py

# Use tini as entrypoint
ENTRYPOINT ["/usr/bin/tini", "--"]

# Use shell form to properly handle signals
CMD python3 -u main.py